# Generated by Django 4.1.3 on 2022-11-03 18:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_task', models.TextField(max_length=5000, verbose_name='Текст задания')),
                ('task_number', models.CharField(max_length=10, verbose_name='Номер задания')),
                ('department_number', models.IntegerField(verbose_name='Номер отдела')),
                ('permission_number', models.CharField(max_length=10, verbose_name='Номер разрешения')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'задание',
                'verbose_name_plural': 'задания',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.IntegerField(verbose_name='№ отдела')),
                ('user_phone', models.IntegerField(verbose_name='№ телефона')),
                ('department_group', models.IntegerField(choices=[(1, 'УАСП'), (2, 'УСП')], default=None, verbose_name='Управление')),
                ('check_edit', models.BooleanField(default=False, verbose_name='Возможность редактирования')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'сотрудник',
                'verbose_name_plural': 'сотрудники',
            },
        ),
    ]
