# Generated by Django 4.1.3 on 2022-11-03 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo_tasks', '0002_employee_user_first_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='user_first_name',
        ),
    ]
