# Generated by Django 4.1.3 on 2022-11-03 18:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ToDo_tasks', '0003_remove_employee_user_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='<django.db.models.query_utils.DeferredAttribute object at 0x000001E8EC282370>'),
        ),
    ]
