# Generated by Django 4.1.3 on 2022-11-03 19:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ToDo_tasks', '0004_alter_employee_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='first_name',
            field=models.CharField(default=0, max_length=150, verbose_name='Имя'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='last_name',
            field=models.CharField(default=0, max_length=150, verbose_name='Фамилия'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='middle_name',
            field=models.CharField(default=0, max_length=150, verbose_name='Отчество'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
