# Generated by Django 4.1.3 on 2022-11-03 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo_tasks', '0005_employee_first_name_employee_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskmodel',
            name='permission_number',
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.IntegerField(choices=[(0, 'Не указан'), (201, 'Строительный первый'), (202, 'Строительный второй')], default=0, verbose_name='№ отдела'),
        ),
    ]
