# Generated by Django 4.1.3 on 2022-11-03 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo_tasks', '0006_remove_taskmodel_permission_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.IntegerField(choices=[(0, '000 - Не указан'), (201, '201 - Строительный первый'), (202, '202 - Строительный второй')], default=0, verbose_name='№ отдела'),
        ),
    ]
