# Generated by Django 4.1.3 on 2022-11-03 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo_tasks', '0008_alter_taskmodel_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ToDo_tasks.employee', verbose_name='Автор задания'),
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='department_number',
            field=models.IntegerField(choices=[(0, '000 - Не указан'), (201, '201 - Строительный первый'), (202, '202 - Строительный второй')], default=0, verbose_name='Номер отдела'),
        ),
    ]
