# Generated by Django 4.1.3 on 2022-11-07 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo_tasks', '0011_ordersmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordersmodel',
            options={'verbose_name': 'номер заказа', 'verbose_name_plural': 'номера заказов'},
        ),
        migrations.AddField(
            model_name='taskmodel',
            name='task_order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='ToDo_tasks.ordersmodel', verbose_name='Номер заказа'),
            preserve_default=False,
        ),
    ]
