# Generated by Django 4.1.3 on 2022-11-07 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo_tasks', '0012_alter_ordersmodel_options_taskmodel_task_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_name', models.CharField(max_length=250, verbose_name='Номер договора')),
            ],
            options={
                'verbose_name': 'номер договора',
                'verbose_name_plural': 'номера договоров',
            },
        ),
        migrations.CreateModel(
            name='ObjectModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_name', models.CharField(default=None, max_length=250, verbose_name='Наименование объекта')),
            ],
            options={
                'verbose_name': 'наименование объекта',
                'verbose_name_plural': 'наименования объектов',
            },
        ),
        migrations.CreateModel(
            name='StageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_name', models.CharField(max_length=250, verbose_name='Наименование этапа')),
                ('stage_contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ToDo_tasks.contractmodel', verbose_name='Номер договора')),
            ],
            options={
                'verbose_name': 'наименование этапа',
                'verbose_name_plural': 'наименования этапов',
            },
        ),
        migrations.AddField(
            model_name='contractmodel',
            name='contract_object',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='ToDo_tasks.objectmodel', verbose_name='Номер договора'),
        ),
    ]
