# Generated by Django 4.1.3 on 2022-11-09 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo_tasks', '0014_taskmodel_task_contract_taskmodel_task_object_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='taas_change_number',
            field=models.IntegerField(default=None, null=True, verbose_name='Номер изменения'),
        ),
    ]
