# Generated by Django 4.1.3 on 2022-11-09 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo_tasks', '0015_taskmodel_taas_change_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='task_type_work',
            field=models.IntegerField(choices=[(1, 'РД'), (2, 'ПД'), (0, 'Не указан')], default=0, verbose_name='Вид документации:'),
        ),
    ]
