# Generated by Django 4.1.3 on 2022-11-10 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo_tasks', '0017_jobtitlemodel_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskmodel',
            old_name='cpe_sign',
            new_name='cpe_sign_status',
        ),
        migrations.RenameField(
            model_name='taskmodel',
            old_name='second_sign',
            new_name='second_sign_status',
        ),
    ]
