# Generated by Django 4.1.3 on 2022-11-16 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo_tasks', '0018_rename_cpe_sign_taskmodel_cpe_sign_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CpeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpe_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ToDo_tasks.employee', verbose_name='Сотрудник')),
            ],
        ),
        migrations.CreateModel(
            name='CanAcceptModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_accept', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ToDo_tasks.employee', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'принимающий задания',
                'verbose_name_plural': 'принимающие задания',
            },
        ),
    ]
