# Generated by Django 4.1.3 on 2022-11-18 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo_tasks', '0020_alter_cpemodel_options_cpemodel_cpe_object'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommandNumberModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command_number', models.CharField(max_length=15, verbose_name='Номер отдела/Сокращение')),
                ('command_name', models.CharField(max_length=150, verbose_name='Наименование отдела')),
            ],
            options={
                'verbose_name': 'номер отдела',
                'verbose_name_plural': 'номера отделов',
            },
        ),
        migrations.AddField(
            model_name='taskmodel',
            name='cpe_sign_date',
            field=models.DateTimeField(default=None, null=True, verbose_name='Дата и время подписи первого подписанта'),
        ),
        migrations.AddField(
            model_name='taskmodel',
            name='first_sign_date',
            field=models.DateTimeField(default=None, null=True, verbose_name='Дата и время подписи первого подписанта'),
        ),
        migrations.AddField(
            model_name='taskmodel',
            name='second_sign_date',
            field=models.DateTimeField(default=None, null=True, verbose_name='Дата и время подписи первого подписанта'),
        ),
        migrations.AddField(
            model_name='taskmodel',
            name='task_create_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='taskmodel',
            name='task_last_edit',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Дата последнего изменения'),
        ),
        migrations.AddField(
            model_name='taskmodel',
            name='task_status',
            field=models.IntegerField(choices=[(1, 'На подписании'), (2, 'Актуально'), (3, 'На корректировке'), (0, 'Аннулировано')], default=1, verbose_name='Статус задания'),
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='task_change_number',
            field=models.IntegerField(default=0, null=True, verbose_name='Номер изменения'),
        ),
        migrations.CreateModel(
            name='TaskNumbersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_of_task', models.IntegerField(default=2022, verbose_name='Год выдачи заданий')),
                ('count_of_task', models.IntegerField(default=1, verbose_name='Счетчик заданий')),
                ('command_number', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ToDo_tasks.commandnumbermodel')),
            ],
            options={
                'verbose_name': 'счетчик заданий',
                'verbose_name_plural': 'счетчики заданий',
            },
        ),
    ]
