# Generated by Django 4.1.3 on 2022-11-18 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo_tasks', '0021_commandnumbermodel_taskmodel_cpe_sign_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='department_number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ToDo_tasks.commandnumbermodel', verbose_name='Номер отдела'),
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='task_last_edit',
            field=models.DateTimeField(null=True, verbose_name='Дата последнего изменения'),
        ),
    ]
