# Generated by Django 4.1.3 on 2022-11-18 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo_tasks', '0024_taskmodel_incoming_date_taskmodel_incoming_employee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='cpe_comment',
            field=models.TextField(default=None, max_length=5000, null=True, verbose_name='Текст задания'),
        ),
    ]
