# Generated by Django 4.1.3 on 2022-11-19 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo_tasks', '0025_taskmodel_cpe_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='incoming_dep',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_dep_id', to='ToDo_tasks.commandnumbermodel', verbose_name='Отдел принимающий задание'),
        ),
    ]
