# Generated by Django 4.1.3 on 2022-11-19 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo_tasks', '0026_taskmodel_incoming_dep'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='task_workers',
            field=models.BooleanField(default=False, verbose_name='Наличие исполнителей'),
        ),
    ]
