# Generated by Django 4.1.3 on 2022-11-19 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo_tasks', '0027_taskmodel_task_workers'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_status', models.BooleanField(default=False, verbose_name='Статус прочтения')),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ToDo_tasks.taskmodel', verbose_name='Задание')),
                ('worker_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ToDo_tasks.employee', verbose_name='Сотрудник')),
            ],
        ),
    ]
