# Generated by Django 4.1.3 on 2022-11-20 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo_tasks', '0028_workermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='can_make_task',
            field=models.BooleanField(default=True, verbose_name='Возможность выдавать задания'),
        ),
        migrations.AddField(
            model_name='employee',
            name='cpe_flag',
            field=models.BooleanField(default=False, verbose_name='Флаг ГИП (техническая метка)'),
        ),
        migrations.CreateModel(
            name='BackCommentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bad_comment', models.TextField(default=None, max_length=5000, null=True, verbose_name='Текст задания')),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ToDo_tasks.taskmodel', verbose_name='Задание')),
            ],
        ),
    ]
