# Generated by Django 4.1.3 on 2022-11-21 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo_tasks', '0029_employee_can_make_task_employee_cpe_flag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='task_building',
            field=models.CharField(max_length=150, null=True, verbose_name='Здание'),
        ),
    ]
