# Generated by Django 4.1.3 on 2022-11-24 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo_tasks', '0030_taskmodel_task_building'),
    ]

    operations = [
        migrations.AddField(
            model_name='canacceptmodel',
            name='dep_accept',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ToDo_tasks.commandnumbermodel', verbose_name='Отдел за который можно подписаться'),
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='task_number',
            field=models.CharField(max_length=15, verbose_name='Номер задания'),
        ),
    ]
