# Generated by Django 4.1.3 on 2022-11-28 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo_tasks', '0032_alter_taskmodel_incoming_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workermodel',
            options={'verbose_name': 'ответственный исполнитель', 'verbose_name_plural': 'ответственные исполнители'},
        ),
        migrations.CreateModel(
            name='ApproveModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approve_status', models.BooleanField(default=False, verbose_name='Статус подписи')),
                ('approve_date', models.DateTimeField(default=None, null=True, verbose_name='Дата подписания')),
                ('approve_task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ToDo_tasks.taskmodel', verbose_name='Задание')),
                ('approve_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ToDo_tasks.employee', verbose_name='Согласователь')),
            ],
        ),
    ]
