# Generated by Django 4.1.3 on 2022-11-28 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo_tasks', '0033_alter_workermodel_options_approvemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='task_approved',
            field=models.BooleanField(default=False, verbose_name='Согласовано'),
        ),
    ]
