# Generated by Django 4.1.3 on 2022-11-30 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo_tasks', '0035_taskmodel_task_need_approve'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvemodel',
            name='approve_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ToDo_tasks.employee', verbose_name='Согласователь'),
        ),
        migrations.CreateModel(
            name='AttachmentFilesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='', verbose_name='Файл')),
                ('add_data', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата загрузки')),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ToDo_tasks.taskmodel', verbose_name='Задание')),
            ],
        ),
    ]
