# Generated by Django 4.1.3 on 2022-12-15 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo_tasks', '0037_groupdepartmentmodel_alter_attachmentfilesmodel_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='department_group',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ToDo_tasks.groupdepartmentmodel', verbose_name='Управление'),
        ),
    ]
