# Generated by Django 4.1.3 on 2022-12-17 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo_tasks', '0038_alter_employee_department_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarkDocModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark_doc', models.CharField(max_length=5, verbose_name='Краткое название марки')),
                ('mark_doc_full_name', models.CharField(max_length=150, verbose_name='Полное название')),
            ],
            options={
                'verbose_name': 'марка документации',
                'verbose_name_plural': 'марки документации',
            },
        ),
        migrations.AlterModelOptions(
            name='groupdepartmentmodel',
            options={'verbose_name': 'управление', 'verbose_name_plural': 'управления'},
        ),
        migrations.AddField(
            model_name='taskmodel',
            name='task_mark_doc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ToDo_tasks.markdocmodel', verbose_name='Марка документации'),
        ),
    ]
