# Generated by Django 4.1.3 on 2023-05-18 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo_tasks', '0040_alter_taskmodel_task_contract_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='approvemodel',
            options={'verbose_name': 'согласователь задания', 'verbose_name_plural': 'согласователи заданий'},
        ),
        migrations.AlterModelOptions(
            name='backcommentmodel',
            options={'verbose_name': 'комментарий при отказе', 'verbose_name_plural': 'комментарии при отказах'},
        ),
        migrations.AddField(
            model_name='employee',
            name='mailing_list_check',
            field=models.BooleanField(default=True, verbose_name='Получать рассылку'),
        ),
        migrations.AlterField(
            model_name='backcommentmodel',
            name='bad_comment',
            field=models.TextField(default=None, max_length=5000, null=True, verbose_name='Текст комментария'),
        ),
        migrations.AlterField(
            model_name='contractmodel',
            name='contract_object',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='ToDo_tasks.objectmodel', verbose_name='Объект'),
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='cpe_comment',
            field=models.TextField(default=None, max_length=5000, null=True, verbose_name='Текст комментария'),
        ),
        migrations.AlterField(
            model_name='tasknumbersmodel',
            name='year_of_task',
            field=models.IntegerField(default=2023, verbose_name='Год выдачи заданий'),
        ),
    ]
