# Generated by Django 4.1.3 on 2023-05-23 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo_tasks', '0042_favoriteslistmodel_employee_work_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favoriteslistmodel',
            options={'verbose_name': 'список избранного', 'verbose_name_plural': 'списки избранного'},
        ),
        migrations.AlterField(
            model_name='employee',
            name='check_edit',
            field=models.BooleanField(default=True, verbose_name='Возможность редактирования'),
        ),
    ]
