# Generated by Django 4.1.3 on 2023-06-12 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo_tasks', '0044_canchangeworkersmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='personnel_number',
            field=models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='Табельный номер'),
        ),
    ]
