# Generated by Django 4.1.3 on 2023-06-12 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo_tasks', '0045_employee_personnel_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandnumbermodel',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ToDo_tasks.groupdepartmentmodel', verbose_name='Управление'),
        ),
    ]
