# Generated by Django 4.1.3 on 2023-07-13 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo_tasks', '0046_commandnumbermodel_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractmodel',
            name='contract_name',
            field=models.CharField(max_length=650, verbose_name='Номер договора'),
        ),
    ]
