# Generated by Django 4.1.3 on 2023-09-12 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo_tasks', '0048_commandnumbermodel_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractmodel',
            name='show',
            field=models.BooleanField(default=True, verbose_name='Отображать договор'),
        ),
        migrations.AddField(
            model_name='objectmodel',
            name='show',
            field=models.BooleanField(default=True, verbose_name='Отображать объект'),
        ),
    ]
