# Generated by Django 4.1.3 on 2023-09-13 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo_tasks', '0051_alter_taskmodel_task_type_work'),
    ]

    operations = [
        migrations.CreateModel(
            name='DraftTaskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draft_text', models.TextField(max_length=5000, verbose_name='Текст задания')),
                ('draft_building', models.CharField(max_length=150, null=True, verbose_name='Здание')),
                ('draft_create_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания черновика')),
                ('draft_type_work', models.IntegerField(default=0, null=True, verbose_name='Вид документации:')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ToDo_tasks.employee', verbose_name='Автор задания')),
                ('draft_contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ToDo_tasks.contractmodel', verbose_name='Номер контракта')),
                ('draft_mark_doc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ToDo_tasks.markdocmodel', verbose_name='Марка документации')),
                ('draft_object', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ToDo_tasks.objectmodel', verbose_name='Наименование объекта')),
                ('draft_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ToDo_tasks.stagemodel', verbose_name='Этап договора')),
                ('first_sign_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='draft_first_sign_user_employee', to='ToDo_tasks.employee', verbose_name='Первый руководитель')),
                ('second_sign_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='draft_second_sign_user_employee', to='ToDo_tasks.employee', verbose_name='Второй руководитель')),
            ],
            options={
                'verbose_name': 'черновик пользователя',
                'verbose_name_plural': 'черновики пользователей',
            },
        ),
    ]
