# Generated by Django 4.1.3 on 2023-09-13 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo_tasks', '0052_drafttaskmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='drafttaskmodel',
            name='draft_name',
            field=models.CharField(max_length=250, null=True, verbose_name='Наименование черновика'),
        ),
    ]
