# Generated by Django 4.1.3 on 2023-09-13 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo_tasks', '0053_drafttaskmodel_draft_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drafttaskmodel',
            name='draft_building',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Здание'),
        ),
        migrations.AlterField(
            model_name='drafttaskmodel',
            name='draft_mark_doc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ToDo_tasks.markdocmodel', verbose_name='Марка документации'),
        ),
        migrations.AlterField(
            model_name='drafttaskmodel',
            name='draft_name',
            field=models.CharField(max_length=250, null=True, verbose_name='Названеие черновика'),
        ),
        migrations.AlterField(
            model_name='drafttaskmodel',
            name='draft_object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ToDo_tasks.objectmodel', verbose_name='Наименование объекта'),
        ),
        migrations.AlterField(
            model_name='drafttaskmodel',
            name='draft_text',
            field=models.TextField(blank=True, max_length=5000, null=True, verbose_name='Текст задания'),
        ),
        migrations.AlterField(
            model_name='drafttaskmodel',
            name='draft_type_work',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Вид документации:'),
        ),
        migrations.AlterField(
            model_name='drafttaskmodel',
            name='first_sign_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='draft_first_sign_user_employee', to='ToDo_tasks.employee', verbose_name='Первый руководитель'),
        ),
        migrations.AlterField(
            model_name='drafttaskmodel',
            name='second_sign_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='draft_second_sign_user_employee', to='ToDo_tasks.employee', verbose_name='Второй руководитель'),
        ),
    ]
