# Generated by Django 4.1.3 on 2023-09-19 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo_tasks', '0054_alter_drafttaskmodel_draft_building_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='have_connection',
            field=models.BooleanField(default=False, verbose_name='Имеет связь с другими заданиями'),
        ),
    ]
