# Generated by Django 4.1.3 on 2023-09-19 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo_tasks', '0055_taskmodel_have_connection'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectionTaskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dependent_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_dependent_task', to='ToDo_tasks.taskmodel', verbose_name='Зависимое задание')),
                ('original_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_original_task', to='ToDo_tasks.taskmodel', verbose_name='Исходное задание')),
            ],
            options={
                'verbose_name': 'взаимосвязь задания',
                'verbose_name_plural': 'взаимосвязи заданий',
            },
        ),
    ]
