# Generated by Django 4.1.3 on 2023-11-23 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo_tasks', '0055_groupdepartmentmodel_show_taskmodel_have_connection_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityDepModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('name_dep', models.CharField(max_length=350, verbose_name='Наименование организации')),
            ],
            options={
                'verbose_name': 'город/организация',
                'verbose_name_plural': 'города/организации',
                'db_table': 'admin_panel_app_citydepmodel',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='groupdepartmentmodel',
            name='city_dep',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ToDo_tasks.citydepmodel', verbose_name='Город'),
        ),
    ]
