# Generated by Django 4.1.3 on 2023-09-19 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo_tasks', '0056_connectiontaskmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connectiontaskmodel',
            name='original_task',
        ),
        migrations.AddField(
            model_name='connectiontaskmodel',
            name='number_connection',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Номер взаимосвязи:'),
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='have_connection',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Номер взаимосвязи с другими заданиями'),
        ),
    ]
