# Generated by Django 4.1.3 on 2023-11-23 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo_tasks', '0056_citydepmodel_groupdepartmentmodel_city_dep'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoreDetailsEmployeeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Файл')),
                ('outside_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Внешняя почта')),
                ('mobile_phone', models.CharField(blank=True, max_length=30, null=True, verbose_name='Мобильный телефон')),
                ('date_birthday', models.DateField(blank=True, null=True, verbose_name='День рождения')),
                ('room', models.CharField(blank=True, max_length=30, null=True, verbose_name='Номер комнаты')),
                ('date_birthday_show', models.BooleanField(default=False, null=True, verbose_name='Отображать день рождения')),
            ],
            options={
                'verbose_name': 'дополнительная информация по сотруднику',
                'verbose_name_plural': 'дополнительная информация по сотрудникам',
                'db_table': 'admin_panel_app_moredetailsemployeemodel',
                'managed': False,
            },
        ),
    ]
