# Generated by Django 4.1.3 on 2023-09-26 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo_tasks', '0059_alter_connectiontaskmodel_number_connection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupdepartmentmodel',
            name='show',
            field=models.BooleanField(default=True, verbose_name='Отображать отдел'),
        ),
    ]
