from django.urls import path
from . import views
from django.contrib.auth.views import PasswordChangeView, LoginView

urlpatterns = [
    path('', views.AboutView.as_view(), name='about'),
    path('index/', views.IndexView.as_view(), name='index'),
    path('my_outgoing_tasks/', views.UserTaskView.as_view(), name='my_tasks'),
    path('inbox', views.MyInboxListView.as_view(), name='inbox'),
    path('my_tasks_on_sign/', views.UserTaskOnSignView.as_view(), name='my_tasks_on_sign'),
    path('add_task/', views.AddTaskView.as_view(), name='add_task'),
    # path('add_task/<int:pk>', views.AddTaskView.as_view(), name='add_task'),  # просмотр добавленного задания
    path('add_task_change/<int:pk>', views.AddChangeTaskView.as_view(), name='add_task_change'),
    path('issued_tasks/', views.IssuedTasksView.as_view(), name="issued_tasks"),
    path('outgoing_tasks/', views.OutgoingTasksView.as_view(), name="outgoing_tasks"),
    path('details/<int:pk>', views.DetailView.as_view(), name='details'),
    path('ajax/load-contracts/', views.load_contracts, name='ajax_load_contracts'),
    path('ajax/load-stages/', views.load_stages, name='ajax_load_stages'),
    path('ajax/inc_emp/', views.load_incoming_employee, name='ajax_load_inc_emp'),
    path('change_password/', PasswordChangeView.as_view(
        template_name='todo_tasks/system_user/change_password.html',
        success_url='/'), name='change_password'),
    path('details/<int:pk>/change', views.EditTaskView.as_view(), name='change'),
    path('details/<int:pk>/change_files', views.EditTaskFiles.as_view(), name='change_files'),
    path('details_to_sign/<int:pk>', views.ToSignDetailView.as_view(), name='details_to_sign'),
    path('details_to_add_workers/<int:pk>', views.ToAddWorkersDetailView.as_view(), name='details_to_add_workers'),
    path('outgoing_to_sign/', views.ToSignListView.as_view(), name='outgoing_to_sign'),
    path("incoming_to_dep/", views.IncomingDepView.as_view(), name='incoming_to_dep'),
    path("incoming_to_sign/", views.IncomingListView.as_view(), name='incoming_to_sign'),
    path("incoming_to_sign_details/<int:pk>", views.IncomingSignDetails.as_view(), name='incoming_to_sign_details'),
    path('incoming_to_workers/', views.ToWorkerListView.as_view(), name='incoming_to_workers'),
    path('search_result/<str:pk>', views.SearchView.as_view(), name='search_result'),
    path('advanced_search/', views.AdvancedSearchView.as_view(), name='advanced_search'),
    path('temp_to_read_task/<int:pk>', views.MyInboxReadTask.as_view(), name='read_task'),
    path('temp_to_delete_worker/<int:pk>', views.ToAddWorkersDetailView.as_view(), name='delete_worker'),
    path('edit_workers/', views.EditWorkerListView.as_view(), name='edit_workers'),
    path('edit_workers_add/<int:pk>', views.EditWorkersDetailView.as_view(), name='edit_workers_add'),
    # path('test_view/', views.TestView.as_view(), name='test_view'),
    path('approve_list_to_sign/', views.ApproveListView.as_view(), name='approve_list_to_sign'),
    path('approve_details/<int:pk>', views.ApproveDetailView.as_view(), name='approve_details'),
    path('download_file/<int:pk>', views.DownloadFileView.as_view(), name='download_file'),
    path('download_blank/<int:pk>', views.DownloadBlankView.as_view(), name='download_blank'),
    path('change_workers/<int:pk>', views.EditWorkersDetailView.as_view(), name='change_workers'),
    path('profile', views.UserProfileView.as_view(), name='profile'),
    path('edit_profile', views.EditProfileUserView.as_view(), name='edit_profile'),
    path('edit_approve/<int:pk>', views.EditApproveUserView.as_view(), name='edit_approve'),
    path('modal-login', LoginView.as_view(), name='login-modal'),
    path('favorites/', views.FavoritesListView.as_view(), name='favorites'),
    path('favorites/<int:pk>', views.CurrentFavoritesListView.as_view(), name='favorite_list'),
    path('share_favorites/<int:pk>', views.ShareFavoritesListView.as_view(), name='share_favorites'),
    path('edit_favorites/<int:pk>', views.EditFavoriteListView.as_view(), name='edit_favorites'),
    path('delete_share_favorites/<int:pk>', views.DeleteShareFavoritesListView.as_view(),
         name='delete_share_favorites'),
    path('add_task_to_favorites/<int:pk>', views.AddTaskFavoritesListView.as_view(), name='add_task_to_favorites'),
    path('delete_task_from_favorites/<int:pk>', views.DeleteTaskFromFavoriteView.as_view(),
         name='delete_task_from_favorites'),
    path('delete_self/<int:pk>', views.DeleteApproveSelf.as_view(), name='delete_self'),
    path('ajax/load_employee', views.load_empolyee, name="ajax_load_employee"),
    path('add_approve_redirect/<int:pk>', views.RedirectApproveUserView.as_view(), name='redirect_approve')
]
